name: RDP-PLAYIT-PASTI-TEMBUS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Gaspol-Playit
      shell: pwsh
      run: |
        Write-Host "Memasang kabel data Playit..."
        # Download Playit
        Invoke-WebRequest -Uri https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-amd64.exe -OutFile playit.exe
        
        Write-Host "=============================="
        Write-Host "KLIK LINK DI BAWAH BUAT AKTIFIN"
        Write-Host "=============================="
        
        # Jalankan Playit
        ./playit.exe
        
