name: RDP-IPV6-SAKTI
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Buka-Jalur-Langsung
      shell: pwsh
      run: |
        Write-Host "Membuka gerbang IPv6..."
        # Mengaktifkan Teredo (jalur akses remote bawaan Windows)
        netsh interface teredo set state enterpriseclient
        
        Write-Host "=============================="
        Write-Host "IP RDP KAMU (CEK YANG IPv6):"
        # Menampilkan IP Mesin
        ipconfig
        Write-Host "=============================="
        
        # Biarkan standby 6 jam
        Start-Sleep -Seconds 21600
        
