name: RDP-Sakti-Fix
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Gas
      shell: pwsh
      run: |
        net user runneradmin Sakti123! /add
        net localgroup administrators runneradmin /add
        # Pakai Chocolatey biar download-nya otomatis dan gak gampang mati linknya
        choco install ngrok
        ngrok config add-authtoken3B3DQ6lO2q6Wj0Nf6sLXu2q1Iaz_3vsC3sLSY29SgvsF6tC6h
        Start-Process ngrok -ArgumentList "tcp 3389"
        Write-Host "Tunggu 15 detik biar tunnel konek..."
        Start-Sleep -Seconds 15
        $tunnels = curl.exe -s http://127.0.0.1:4040/api/tunnels | ConvertFrom-Json
        Write-Host "ALAMAT RDP KAMU: $($tunnels.tunnels[0].public_url)"
        while($true){ Write-Host "Windows Aktif..."; Start-Sleep -Seconds 60 }
        
