name: Windows-CRD-Super-Cheat-Audio
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Pasang CRD Jalur Aman
        run: |
          # Download CRD Resmi (Link ini pasti aman, bukan novel)
          $crdUrl = "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi"
          Invoke-WebRequest $crdUrl -OutFile "crd.msi"
          Start-Process msiexec.exe -ArgumentList "/i crd.msi /qn /norestart" -Wait

      - name: Cara Curang Aktifin Audio Tanpa Download
        run: |
          # 1. Paksa servis audio bangun dari kubur
          sc.exe config audiosrv start= auto
          sc.exe config AudioEndpointBuilder start= auto
          net start audiosrv
          net start AudioEndpointBuilder
          
          # 2. Suntik Registry agar RDP mau ngirim suara
          reg add "HKLM\System\CurrentControlSet\Control\Terminal Server\WinStations" /v ConsoleAudio /t REG_DWORD /d 1 /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Drivers32" /v wave /t REG_SZ /d wdmaud.drv /f
          reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Drivers32" /v midi /t REG_SZ /d wdmaud.drv /f

      - name: Eksekusi Kode Google
        shell: powershell
        run: |
          $PIN = "1234567"
          & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="4/0Aci98E9-6S65P1bowVoiuPIP7tfIoe02hljRyHSWg6YoLwuZ_l8CKgLT1JlW514cQfn-0g" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin=$PIN

      - name: Online 6 Jam
        run: |
          while($true) { Write-Host "Server Aktif. PIN: 1234567. Cek Audio!"; Start-Sleep -Seconds 60 }
          
