name: Windows-Sultan-Zan
on: 
  workflow_dispatch:
    inputs:
      crd_code:
        description: 'Masukkan kode CRD Debian (Mulai dari DISPLAY=...)'
        required: true
        default: ''

jobs:
  nyalain-windows:
    runs-on: ubuntu-latest
    steps:
    - name: 📦 Memasang Alat Tempur (QEMU & CRD)
      run: |
        sudo apt update
        sudo apt install -y qemu-system-x86 chrome-remote-desktop
        
    - name: ⏬ Download ISO & Buat Disk
      run: |
        # Menggunakan wget untuk ambil ISO Windows 10 Pro
        wget -q https://archive.org/download/win10pro_202403/win10pro.iso
        qemu-img create -f qcow2 win10.qcow2 50G

    - name: 🔐 Mengaktifkan CRD dari Input
      run: |
        # Mengambil kode yang kamu ketik di kotak input tadi
        ${{ github.event.inputs.crd_code }} --pin=123456 --name=GITHUB-SULTAN-ZAN

    - name: 🏎️ GASPOL WINDOWS 10 PRO
      run: |
        # Menjalankan QEMU dengan RAM standar Azure (7GB biar aman)
        sudo qemu-system-x86_64 -m 7G -smp cores=2 -cpu host -drive file=win10.qcow2,format=qcow2 -cdrom win10pro.iso -vga virtio -net nic -net user -device virtio-tablet-pci -boot d
        
