name: Windows7_Izan_Final_Beneran
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Amunisi Mekanik (QEMU & Cloudflare)
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86 novnc websockify qemu-utils
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: 2. Download ISO Windows 7 Lite (Link Direct)
        run: |
          # Pakai link direct download biar gak kena 503 Service Unavailable
          wget -O win7.iso "https://cdn.pixeldrain.com/api/file/QY8A3pCj" || \
          wget -O win7.iso "https://ia801501.us.archive.org/21/items/win-7-super-lite-edition-x-86/Win7_Super_Lite_Edition_x86.iso"

      - name: 3. Goreng Windows 7 (RAM 8GB + AMD EPYC)
        run: |
          qemu-img create -f qcow2 windows.qcow2 20G
          
          sudo qemu-system-x86_64 \
            -m 8G \
            -smp 2 \
            -cpu host \
            -enable-kvm \
            -drive file=windows.qcow2,format=qcow2 \
            -cdrom win7.iso \
            -device usb-ehci,id=usbbus \
            -device usb-tablet,bus=usbbus.0 \
            -vnc 0.0.0.0:0 \
            -vga std \
            -boot d \
            -display none &

          sleep 20
          websockify --web /usr/share/novnc/ 6080 0.0.0.0:5900 &
          
          echo "✅ Windows lagi dipanasin... Kalau 503 berarti servernya lagi tidur!"
          sleep 60

      - name: 4. Sajikan Link Windows 7 VVIP
        run: |
          echo "-------------------------------------------------------"
          echo "🚀 IZAN, COBA JALUR CADANGAN!"
          echo "-------------------------------------------------------"
          cloudflared tunnel --url http://127.0.0.1:6080
          
